# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e937b12c78a6e0f03d2f68a4ac504d5873a3014138a966c0c782b6c33c78d83bd88c98c3ba06d791ad3f20715293683ac924077cbc0d8c3861e798d1ecfe9ea

test:
  secret_key_base: 5e626521df31bf7b2e164787502d76b9bc64064ac598cfce25504cdc42d9048a5b9db1372535f68e140473820d55a0bb7178a65f9f5b29dfca4bd1450ce0cf98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
